# Generated by Django 2.1.2 on 2019-02-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.IntegerField()),
                ('github_name', models.TextField()),
                ('github_full_name', models.TextField()),
                ('open_issues_count', models.IntegerField()),
                ('owner_login', models.TextField()),
            ],
        ),
    ]
