# Generated by Django 2.1.2 on 2019-02-05 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_number', models.IntegerField()),
                ('github_html_url', models.TextField()),
                ('github_state', models.TextField()),
                ('github_title', models.TextField()),
                ('github_body', models.TextField()),
                ('label', models.TextField()),
                ('github_created_at', models.DateTimeField()),
                ('github_updated_at', models.DateTimeField()),
                ('github_comments_number', models.IntegerField()),
                ('priority', models.IntegerField(choices=[(1, '1 - HIGH'), (2, '2 - MEDIUM'), (3, '3 - LOW')], default=3)),
                ('deadline', models.DateTimeField()),
                ('github_assignee_login', models.TextField()),
                ('github_assignee_url_profile', models.TextField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Repository')),
            ],
        ),
    ]
